name: Build And Release to App Store

on:
  # Triggers the workflow on any pull request and push to develop
  # push:
  #   branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Make the git branch for a PR available to our Fastfile
  MX_GIT_BRANCH: ${{ github.event.pull_request.head.ref }}

jobs:
  build:
    name: Build
    runs-on: macos-12
    
    # Concurrency group not needed as this workflow only runs on develop which we always want to test.

    steps:
      - uses: actions/checkout@v2

      # Common cache
      # Note: GH actions do not support yaml anchor yet. We need to duplicate this for every job
      - uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      # Make sure we use the latest version of MatrixSDK
      - name: Reset MatrixSDK pod
        run: rm -rf Pods/MatrixSDK

      - name: Prepare Element IOS
        run: |
          git clone https://github.com/vector-im/element-ios.git
          cd element-ios
          git checkout master
          cd ..

          rm -rf element-ios/.github

      - name: Edit Config
        run: |
          sed -i '' -e "s#\"https://matrix.org\"#\"https://${HOMESERVER}\"#g" element-ios/Config/BuildSettings.swift
        env:
          HOMESERVER: ${{ secrets.HOMESERVER }}

      - name: Change different identifiers
        run: | 

          # Changes in Config/AppIdentifiers

          sed -i '' -e "s#BUNDLE_DISPLAY_NAME = Element#BUNDLE_DISPLAY_NAME = ${BUNDLE_DISPLAY_NAME}#g" element-ios/Config/AppIdentifiers.xcconfig
          sed -i '' -e "s#BASE_BUNDLE_IDENTIFIER = im.vector.app#BASE_BUNDLE_IDENTIFIER = ${BASE_BUNDLE_IDENTIFIER}#g" element-ios/Config/AppIdentifiers.xcconfig
          sed -i '' -e "s#APPLICATION_GROUP_IDENTIFIER = group.im.vector#APPLICATION_GROUP_IDENTIFIER = ${GROUP_ID}#g" element-ios/Config/AppIdentifiers.xcconfig
          sed -i '' -e "s#DEVELOPMENT_TEAM = 7J4U792NQT#DEVELOPMENT_TEAM = ${TEAM_ID}#g" element-ios/Config/AppIdentifiers.xcconfig
          
          sed -i '' -e "s#RIOT_PROVISIONING_PROFILE_SPECIFIER = Vector App Store#RIOT_PROVISIONING_PROFILE_SPECIFIER = \"${MAIN_PROVISIONING_PROFILE_NAME}\"#g" element-ios/Config/AppIdentifiers.xcconfig
          sed -i '' -e "s#NSE_PROVISIONING_PROFILE_SPECIFIER = \"Vector NSE: App Store\"#NSE_PROVISIONING_PROFILE_SPECIFIER = \"${NSE_PROVISIONING_PROFILE_NAME}\"#g" element-ios/Config/AppIdentifiers.xcconfig
          sed -i '' -e "s#SHARE_EXTENSION_PROVISIONING_PROFILE_SPECIFIER = \"Vector Share Extension: App Store\"#SHARE_EXTENSION_PROVISIONING_PROFILE_SPECIFIER = \"${SHARE_EXTENSION_PROVISIONING_PROFILE_NAME}\"#g" element-ios/Config/AppIdentifiers.xcconfig
          sed -i '' -e "s#SIRI_INTENTS_PROVISIONING_PROFILE_SPECIFIER = \"Vector Siri Intents: App Store\"#SIRI_INTENTS_PROVISIONING_PROFILE_SPECIFIER = \"${SIRI_INTENTS_PROVISIONING_PROFILE_NAME}\"#g" element-ios/Config/AppIdentifiers.xcconfig
          
          # Changes in fastlane/.env.default

          sed -i '' -e "s#IPA_NAME=Riot#IPA_NAME=CustomElement#g" element-ios/fastlane/.env.default

          # Bundle_id
          sed -i '' -e "s#MAIN_BUNDLE_ID=im.vector.app#MAIN_BUNDLE_ID=${BASE_BUNDLE_IDENTIFIER}#g" element-ios/fastlane/.env.default
          sed -i '' -e "s#SHARE_EXTENSION_BUNDLE_ID=im.vector.app.shareExtension#SHARE_EXTENSION_BUNDLE_ID=${BASE_BUNDLE_IDENTIFIER}.shareExtension#g" element-ios/fastlane/.env.default
          sed -i '' -e "s#SIRI_INTENTS_EXTENSION_BUNDLE_ID=im.vector.app.SiriIntents#SIRI_INTENTS_EXTENSION_BUNDLE_ID=${BASE_BUNDLE_IDENTIFIER}.SiriIntents#g" element-ios/fastlane/.env.default
          sed -i '' -e "s#NSE_BUNDLE_ID=im.vector.app.nse#NSE_BUNDLE_ID=${BASE_BUNDLE_IDENTIFIER}.nse#g" element-ios/fastlane/.env.default
          
          # Code Signing
          sed -i '' -e "s#APPSTORE_CODESIGNING_IDENTITY=\"Apple Distribution: Vector Creations Limited (7J4U792NQT)\"#APPSTORE_CODESIGNING_IDENTITY=\"${DISTRIBUTION_CERTIFICATE_NAME}\"#g" element-ios/fastlane/.env.default
          sed -i '' -e "s#APPSTORE_SIGNING_CERTIFICATE=\"Apple Distribution: Vector Creations Limited (7J4U792NQT)\"#APPSTORE_SIGNING_CERTIFICATE=\"${DISTRIBUTION_CERTIFICATE_NAME}\"#g" element-ios/fastlane/.env.default
          
          # Provisioning profiles
          sed -i '' -e "s#APPSTORE_MAIN_PROVISIONING_PROFILE_SPECIFIER=\"Vector App Store\"#APPSTORE_MAIN_PROVISIONING_PROFILE_SPECIFIER=\"${MAIN_PROVISIONING_PROFILE_NAME}\"#g" element-ios/fastlane/.env.default
          sed -i '' -e "s#APPSTORE_NSE_PROVISIONING_PROFILE_SPECIFIER=\"Vector NSE: App Store\"#APPSTORE_NSE_PROVISIONING_PROFILE_SPECIFIER=\"${NSE_PROVISIONING_PROFILE_NAME}\"#g" element-ios/fastlane/.env.default
          sed -i '' -e "s#APPSTORE_SHARE_EXTENSION_PROVISIONING_PROFILE_SPECIFIER=\"Vector Share Extension: App Store\"#APPSTORE_SHARE_EXTENSION_PROVISIONING_PROFILE_SPECIFIER=\"${SHARE_EXTENSION_PROVISIONING_PROFILE_NAME}\"#g" element-ios/fastlane/.env.default
          sed -i '' -e "s#APPSTORE_SIRI_INTENTS_EXTENSION_PROVISIONING_PROFILE_SPECIFIER=\"Vector Siri Intents: App Store\"#APPSTORE_SIRI_INTENTS_EXTENSION_PROVISIONING_PROFILE_SPECIFIER=\"${SIRI_INTENTS_PROVISIONING_PROFILE_NAME}\"#g" element-ios/fastlane/.env.default
          
          sed -i '' -e "s#TEAM_ID=7J4U792NQT#TEAM_ID=${TEAM_ID}#g" element-ios/fastlane/.env.default
        
        env:
          BUNDLE_DISPLAY_NAME: ${{ secrets.BUNDLE_DISPLAY_NAME }}
          BASE_BUNDLE_IDENTIFIER: ${{ secrets.BASE_BUNDLE_IDENTIFIER }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          MAIN_PROVISIONING_PROFILE_NAME: ${{ secrets.MAIN_PROVISIONING_PROFILE_NAME }}
          NSE_PROVISIONING_PROFILE_NAME: ${{ secrets.NSE_PROVISIONING_PROFILE_NAME }}
          SHARE_EXTENSION_PROVISIONING_PROFILE_NAME: ${{ secrets.SHARE_EXTENSION_PROVISIONING_PROFILE_NAME }}
          SIRI_INTENTS_PROVISIONING_PROFILE_NAME: ${{ secrets.SIRI_INTENTS_PROVISIONING_PROFILE_NAME }}
          DISTRIBUTION_CERTIFICATE_NAME: ${{ secrets.DISTRIBUTION_CERTIFICATE_NAME }}

      - name: Display .env.default file
        run: cat element-ios/fastlane/.env.default
      - name: Display AppIdentifiers.xcconfig file
        run: cat element-ios/Config/AppIdentifiers.xcconfig

      # Возможно в Riot/SupportingFiles/Info.plist на самом деле нужно будет менять только значение ключа ITSEncryptionExportComplianceCode, а не весь блок 
      - name: Merge Repositories
        run: |
          mv element-ios/* ./
          rm fastlane/Fastfile
          rm Riot/SupportingFiles/Info.plist
          mv Fastfile fastlane/Fastfile
          mv Info.plist Riot/SupportingFiles/Info.plist

      - name: Delete Diawi plugin 
        run: |
          sed -i '' "/gem 'fastlane-plugin-diawi'/d" fastlane/Pluginfile
          sed -i '' -e '/fastlane-plugin-diawi (2.1.0)/d' Gemfile.lock
          sed -i '' -e '/fastlane-plugin-diawi/d' Gemfile.lock

      # Common setup
      # Note: GH actions do not support yaml anchor yet. We need to duplicate this for every job
      - name: Brew bundle
        run: brew bundle
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Use right MatrixSDK versions
        run: bundle exec fastlane point_dependencies_to_related_branches

      # Import private signing certificate
      - name: Import signing certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATE_P12 }}
          p12-password: ${{ secrets.CERTIFICATE_P12_PASSWORD }}

      # Main step
      - name: Deploy and release IOS app 
        run: bundle exec fastlane deploy_release 
        env:
          APPSTORECONNECT_KEY_ID: ${{ secrets.APPSTORECONNECT_KEY_ID }}
          APPSTORECONNECT_KEY_ISSUER_ID: ${{ secrets.APPSTORECONNECT_KEY_ISSUER_ID }}
          APPSTORECONNECT_KEY_CONTENT: ${{ secrets.APPSTORECONNECT_KEY_CONTENT }}